Completed exercise prep-javascript-arrays.
waqas-ahmedd/prep-0922-code-solutions pull request #12
Opened 2022-09-26 00:44 UTC by waqas-ahmedd

<img width="1283" alt="Screen Shot 2022-09-25 at 5 42 26 PM" src="https://user-images.githubusercontent.com/100913392/192173757-52ab1b95-40f1-43c5-9e76-582bec35e29b.png">

2022-09-26 16:57 UTC, thebearingedge requested changes

2022-09-26 16:57 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +var lastElement = languagues[5];
You can get the last element of any array by subtracting one from the array's length

```js
var lastElement = languages[length - 1];
```

2022-09-26 22:46 UTC, waqas-ahmedd commented
<img width="1020" alt="Screen Shot 2022-09-26 at 3 44 34 PM" src="https://user-images.githubusercontent.com/100913392/192393938-3a69628b-71f8-45a4-bf6b-7dc4b51ccf90.png">

2022-09-27 01:33 UTC, thebearingedge approved these changes

2022-09-27 01:33 UTC, merged